export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
}

export const productConstants = {
    GET_PRODUCT_BY_SLUG_REQUEST: 'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_SUCCESS: 'GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_FAILURE: 'GET_PRODUCT_BY_SLUG_FAILURE',
}