export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
}

export const productConstants = {
    GET_PRODUCT_BY_SLUG_REQUEST: 'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_SUCCESS: 'GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_FAILURE: 'GET_PRODUCT_BY_SLUG_FAILURE',

    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE',
}

export const pageConstants = {
    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',
}

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const cartConstants = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

    RESET_CART_REQUEST: 'RESET_CART_REQUEST',
    RESET_CART_SUCCESS: 'RESET_CART_SUCCESS',
    RESET_CART_FAILURE: 'RESET_CART_FAILURE',
}

export const userConstants = {
    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',

    ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_RFAILURE',

    ADD_USER_ORDER_REQUEST: 'ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS: 'ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILURE: 'ADD_USER_ORDER_RFAILURE',

    GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_FAILURE: 'GET_USER_ORDER_RFAILURE',
}